#!/usr/bin/env python3
r"""
Generate LaTeX \input lines from master_core_structure.yaml.

Usage (from repo root):

    python tools/generate_auto_inputs.py
    python tools/generate_auto_inputs.py path/to/your.yaml

The script writes all discovered .tex files from the YAML (in order)
into content/_auto_core_inputs.tex as:

    \input{content/whatever_without_extension}

YAML format (supported variants):

1) Top-level list of nodes:

   - title: Introduction
     file: content/01_intro.tex
   - title: K-levels
     file: content/k_levels/klevels_master.tex
     children:
       - title: K0
         file: content/k_levels/k0.tex

2) Top-level dict with one of the keys: root / sections / nodes:

   root:
     - title: ...
       file: ...
"""

import os
import sys
from typing import Any, Dict, List

import yaml  # pip install pyyaml

# ------------------------------------------------------------
# Settings
# ------------------------------------------------------------

STRUCTURE_FILE = sys.argv[1] if len(sys.argv) > 1 else "master_core_structure.yaml"
OUTPUT_TEX = "content/_auto_core_inputs.tex"


# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

def load_nodes(path: str) -> List[Dict[str, Any]]:
    """Try to load a list of nodes from YAML.

    Returns an empty list if the structure is not recognized, but does not crash.
    """
    if not os.path.exists(path):
        print(f"[inputs] YAML file not found: {path}")
        return []

    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if data is None:
        print("[inputs] YAML is empty, nothing to generate.")
        return []

    # Case 1: top-level list
    if isinstance(data, list):
        return data

    # Case 2: top-level dict with known key
    if isinstance(data, dict):
        for key in ("root", "sections", "nodes"):
            value = data.get(key)
            if isinstance(value, list):
                return value

    # Unknown structure: soft fail
    print("⚠️  Не могу понять структуру YAML для auto-inputs. "
          "Ожидал list или ключи root/sections/nodes.")
    return []


def walk_nodes(nodes: List[Dict[str, Any]]) -> List[str]:
    """Flatten tree of nodes into an ordered list of file paths."""
    result: List[str] = []

    def _walk(subnodes: List[Dict[str, Any]]) -> None:
        for node in subnodes:
            if not isinstance(node, dict):
                continue
            file_path = node.get("file")
            if file_path and isinstance(file_path, str):
                result.append(file_path)
            children = (
                node.get("children")
                or node.get("subsections")
                or []
            )
            if isinstance(children, list) and children:
                _walk(children)

    _walk(nodes)
    return result


def tex_path_without_ext(path: str) -> str:
    """Convert 'content/foo.tex' -> 'content/foo'."""
    if path.lower().endswith(".tex"):
        return path[:-4]
    return path


def write_auto_inputs(tex_files: List[str], output_path: str) -> None:
    """Write \input lines (or just a comment if list is empty)."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    lines: List[str] = []
    lines.append("% AUTO-GENERATED FILE — DO NOT EDIT MANUALLY\n")
    lines.append("% This file is generated by tools/generate_auto_inputs.py\n\n")

    if not tex_files:
        lines.append("% No sections defined in master_core_structure.yaml yet.\n")
    else:
        for p in tex_files:
            lines.append(f"\\input{{{tex_path_without_ext(p)}}}\n")

    with open(output_path, "w", encoding="utf-8") as f:
        f.writelines(lines)

    print(f"[inputs] Written {len(tex_files)} \\input lines to {output_path}")


# ------------------------------------------------------------
# main
# ------------------------------------------------------------

def main() -> None:
    print(f"[inputs] Using YAML: {STRUCTURE_FILE}")
    nodes = load_nodes(STRUCTURE_FILE)
    tex_files = walk_nodes(nodes) if nodes else []
    write_auto_inputs(tex_files, OUTPUT_TEX)


if __name__ == "__main__":
    main()
