#!/usr/bin/env python3
"""
Generate a LaTeX include file with \\input{...} lines
based on master_core_structure.yaml.

Output:
    content/_auto_core_inputs.tex

Usage (from repo root):

    python tools/generate_inputs_from_yaml.py
"""

import os
import yaml

STRUCTURE_FILE = "master_core_structure.yaml"
OUTPUT_FILE = "content/_auto_core_inputs.tex"


def load_nodes(path: str):
    """Same tolerant loader as in generator/validator."""
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if data is None:
        raise SystemExit("YAML пустой. Ожидал список секций.")

    if isinstance(data, list):
        return data

    if isinstance(data, dict):
        for key in ("root", "sections", "nodes", "chapters", "toc", "content"):
            value = data.get(key)
            if isinstance(value, list):
                return value

        for value in data.values():
            if isinstance(value, list) and (not value or isinstance(value[0], dict)):
                return value

        nodes = []
        for key, value in data.items():
            node = {"title": str(key)}
            if isinstance(value, dict):
                node.update(value)
            nodes.append(node)
        return nodes

    raise SystemExit(
        "Не могу понять структуру YAML даже после всех попыток. "
        "Ожидал list или dict."
    )


def flatten_files(nodes, acc=None):
    """DFS → список файлов в порядке обхода (без дубликатов)."""
    if acc is None:
        acc = []
    seen = set(acc)

    def _walk(ns):
        nonlocal acc, seen
        for node in ns:
            if not isinstance(node, dict):
                continue
            fpath = node.get("file")
            if fpath:
                norm = os.path.normpath(fpath)
                if norm not in seen:
                    seen.add(norm)
                    acc.append(norm)
            children = node.get("children") or node.get("subsections") or []
            if children:
                _walk(children)

    _walk(nodes)
    return acc


def main():
    if not os.path.exists(STRUCTURE_FILE):
        raise SystemExit(f"YAML не найден: {STRUCTURE_FILE}")

    print(f"[inputs] Using YAML: {STRUCTURE_FILE}")
    nodes = load_nodes(STRUCTURE_FILE)
    files = flatten_files(nodes)

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(
            "% ======================================================================\n"
            "%  AUTO-GENERATED INPUT LIST\n"
            "%  DO NOT EDIT BY HAND — generated by tools/generate_inputs_from_yaml.py\n"
            "% ======================================================================\n\n"
        )
        for fpath in files:
            # drop .tex extension for \\input
            without_ext = os.path.splitext(fpath)[0]
            f.write(f"\\input{{{without_ext}}}\n")

    print(f"[inputs] Written {len(files)} \\input lines to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
