RELEASE_ID = "oc_core_1_3_2"
VERSION = "1.3.2"
TIMESTAMP = "2026-04-25T00:00:00Z"
PREVIOUS_VERSION = "1.3.1"
PREVIOUS_DOI = "10.5281/zenodo.19741958"
CONCEPT_DOI = "10.5281/zenodo.17899134"
DOI_PENDING = "TBD_UNTIL_ZENODO_NEW_VERSION_PUBLISHED"

GATE_STATES = {"PASS", "WARN", "FAIL", "BLOCKED", "NOT_APPLICABLE", "NOT_RUN"}
SEVERITIES = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"}
RELEASE_STATES = {
    "DRAFT",
    "INTERNAL_RC",
    "SHIT_CONTROL_RUNNING",
    "REMEDIATION_REQUIRED",
    "RELEASE_READY_NO_SEND",
    "OWNER_APPROVED_FOR_CHANNEL",
    "PUBLISHING",
    "PUBLISHED_PENDING_POSTFLIGHT",
    "PUBLIC_RELEASE_VERIFIED",
    "PUBLIC_RELEASE_DEFECT_FOUND",
    "SUPERSEDED",
    "RETRACTED",
}
